spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ketan_stores
    username: springstudent
    password: springstudent
    # url: jdbc:mysql://localhost:3307/ketan_stores
    # username: root
    # password: Krishrakesh1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      password: spring
